some little things

diff --git a/.config/hypr/scripts/colorpicker b/.config/hypr/scripts/colorpicker
--- a/.config/hypr/scripts/colorpicker
+++ b/.config/hypr/scripts/colorpicker
@@ -1,12 +1,29 @@
 #!/bin/bash
 
+# Lock file path
+LOCKFILE=/tmp/color_picker.lock
+
+# Create a lock file if it doesn't exist, or exit if it does
+if [ -e "$LOCKFILE" ]; then
+    echo "Script is already running. Exiting."
+    exit 1
+else
+    touch "$LOCKFILE"
+fi
+
+# Function to remove the lock file upon script exit
+cleanup() {
+    rm -f "$LOCKFILE"
+}
+trap cleanup EXIT
+
 TMPPCK=$(hyprpicker -a -n)
 TMPPST=$(wl-paste)
 CMD=$(echo "$TMPPST")
 TMP=/tmp/xcolor_$CMD.png
 
 hyprpick() {
-  $TMPPCK
+    $TMPPCK
 }
 
 check_dependencies() {
@@ -27,3 +44,6 @@ main() {
 check_dependencies
 hyprpick
 main
+
+# Remove the lock file before exiting (cleanup function will handle this)
+cleanup
diff --git a/.config/hypr/scripts/screenshot b/.config/hypr/scripts/screenshot
--- a/.config/hypr/scripts/screenshot
+++ b/.config/hypr/scripts/screenshot
@@ -1,15 +1,33 @@
 #!/bin/bash
- 
+
+# Lock file path
+LOCKFILE=/tmp/screenshot_script.lock
+
+# Create a lock file if it doesn't exist, or exit if it does
+if [ -e "$LOCKFILE" ]; then
+    echo "Script is already running. Exiting."
+    exit 1
+else
+    touch "$LOCKFILE"
+fi
+
+# Function to remove the lock file upon script exit
+cleanup() {
+    rm -f "$LOCKFILE"
+}
+trap cleanup EXIT
+
 SAVEDIR=~/Pictures/Screenshots
 mkdir -p -- "$SAVEDIR"
 FILENAME="$SAVEDIR/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')"
 EXPENDED_FILENAME="${FILENAME/#\~/$HOME}"
- 
+
 grim -g "$(slurp)" "$EXPENDED_FILENAME"
 swappy -f "$EXPENDED_FILENAME" -o "$EXPENDED_FILENAME"
- 
- 
-if wl-copy < "$EXPENDED_FILENAME"
-then
-notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$EXPENDED_FILENAME"
+
+if wl-copy < "$EXPENDED_FILENAME"; then
+    notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$EXPENDED_FILENAME"
 fi
+
+# Remove the lock file before exiting (cleanup function will handle this)
+cleanup
